language: java
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - more-stable

addons:
  sonarqube: true
env:
  global:
    - secure: "rK6ahylLSkG9nXc/maV7F2z0dJD8tnsgx9176e6gRqoCHiBSfhDEg3j/aRn3f+Brhkq8MhSDC9p6bzh8rqYiMe+mgOPiHkkTrdQMaNDOKXRuCWpWO/I4+3H3zXZluxjGW25fKVFqj8XWxzHvn+fj5DaXmhNofWQoHxRBqlf0BYQZ0/gxGGcMtCxvwx/vlVIhWTz10rOQmsoHylFILTqdYlYzXUfKesklB57q6xgBkVSQ7blA526aCfeuyiaCEIxRyEukGK/G5FJHsheSkeYLsuF+qNFYeMtHNZhRVVK/qUZ4oeCBqUExOaZyMCn+LJm9H2mGUdUtExCg6DeS3jz9dXQlSXqVLGhg5G967TuWkggovb7YvQ2C0bO0hNrc1jWGuQTRvqSTvQJa6HPAbzwGXbOGugWY6shHmeENOo2tOXIehr/FB8Q5kb1VuPQwlTvonkOYemmPr+FF9TdPuM8m6I75vaZkleZRUvxCRqOU7mPNVHzqWysu0/9y0wSsE63uqZD+R0K0AfHxewu6iGicrjMSLolgW4MhfLmfaNyQfdWkN5+KXwxo5mRR9Fkvjyfhl5hrr4eV69cTcotcyAS6uhvqT/njzfdvfNhya7UAfTMXURnIofR12T5QyJEjcv5wqQUDcPr0nj4D+yJrqf7Td6vyx5rvWEw4uqyVRXnwWW4="

script:
  # other script steps might be done before running the actual SonarQube analysis
  # - sonar-scanner -Dsonar.login=$SONAR_TOKEN
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN


